'use strict';
/**
 * key/value pairs,
 * order of operators does not matter.
 * Make sure that every operator is assigned a unique integer
 */
export default {  
    ash: 1,
    bandit: 2,
    blitz: 3,
    castle: 4,
    doc: 5,
    fuze: 6,
    glaz: 7,
    iq: 8,
    jager: 9,
    kapkan: 10,
    montagne: 11,
    mute: 12,
    pulse: 13,
    recruit: 14,
    rook: 15,
    sledge: 16,
    smoke: 17,
    tachanka: 18,
    thatcher: 19,
    thermite: 20,
    twitch: 21,
    buck: 22,
    frost: 23,
    blackbeard: 24,
    valkyrie: 25,
    capitao: 26,
    caviera: 27,
    hibana: 28,
    echo: 29,
    jackal:30,
    mira: 31, 
    ying: 32,
    lesion: 33,
    zofia: 34,
    ela: 35,
    dokkaebi: 36,
    vigil: 37,
    finka: 38,
    lion: 39,
    maestro: 40,
    alibi: 41,
    maverick: 42,
    clash: 43,
    nomad: 44,
    kaid: 45,
    gridlock: 46,
    mozzie: 47,
    nokk: 48,
    warden: 49,
    amaru: 50,
    goyo: 51,

};