class ImageLocation {
    static getLocations(fileFormat) {
        return {
            'Ace': 'img/' + fileFormat + '/ace.' + fileFormat,
            'Alibi': 'img/' + fileFormat + '/alibi.' + fileFormat,
            'Amaru': 'img/' + fileFormat + '/amaru.' + fileFormat,
            'Aruni': 'img/' + fileFormat + '/aruni.' + fileFormat,
            'Ash': 'img/' + fileFormat + '/ash.' + fileFormat,
            'Azami': 'img/' + fileFormat + '/azami.' + fileFormat,
            'Bandit': 'img/' + fileFormat + '/bandit.' + fileFormat,
            'Blackbeard': 'img/' + fileFormat + '/blackbeard.' + fileFormat,
            'Blitz': 'img/' + fileFormat + '/blitz.' + fileFormat,
            'Brava': 'img/' + fileFormat + '/brava.' + fileFormat,
            'Buck': 'img/' + fileFormat + '/buck.' + fileFormat,
            'Capitão': 'img/' + fileFormat + '/capitao.' + fileFormat,
            'Castle': 'img/' + fileFormat + '/castle.' + fileFormat,
            'Caveira': 'img/' + fileFormat + '/caveira.' + fileFormat,
            'Clash': 'img/' + fileFormat + '/clash.' + fileFormat,
            'Deimos': 'img/' + fileFormat + '/deimos.' + fileFormat,
            'Doc': 'img/' + fileFormat + '/doc.' + fileFormat,
            'Dokkaebi': 'img/' + fileFormat + '/dokkaebi.' + fileFormat,
            'Echo': 'img/' + fileFormat + '/echo.' + fileFormat,
            'Ela': 'img/' + fileFormat + '/ela.' + fileFormat,
            'Fenrir': 'img/' + fileFormat + '/fenrir.' + fileFormat,
            'Finka': 'img/' + fileFormat + '/finka.' + fileFormat,
            'Flores': 'img/' + fileFormat + '/flores.' + fileFormat,
            'Frost': 'img/' + fileFormat + '/frost.' + fileFormat,
            'Fuze': 'img/' + fileFormat + '/fuze.' + fileFormat,
            'Glaz': 'img/' + fileFormat + '/glaz.' + fileFormat,
            'Goyo': 'img/' + fileFormat + '/goyo.' + fileFormat,
            'Gridlock': 'img/' + fileFormat + '/gridlock.' + fileFormat,
            'Grim': 'img/' + fileFormat + '/grim.' + fileFormat,
            'Hibana': 'img/' + fileFormat + '/hibana.' + fileFormat,
            'Iana': 'img/' + fileFormat + '/iana.' + fileFormat,
            'IQ': 'img/' + fileFormat + '/iq.' + fileFormat,
            'Jackal': 'img/' + fileFormat + '/jackal.' + fileFormat,
            'Jäger': 'img/' + fileFormat + '/jager.' + fileFormat,
            'Kaid': 'img/' + fileFormat + '/kaid.' + fileFormat,
            'Kali':'img/' + fileFormat + '/kali.' + fileFormat,
            'Kapkan': 'img/' + fileFormat + '/kapkan.' + fileFormat,
            'Lesion': 'img/' + fileFormat + '/lesion.' + fileFormat,
            'Lion': 'img/' + fileFormat + '/lion.' + fileFormat,
            'Maestro': 'img/' + fileFormat + '/maestro.' + fileFormat,
            'Maverick': 'img/' + fileFormat + '/maverick.' + fileFormat,
            'Melusi': 'img/' + fileFormat + '/melusi.' + fileFormat,
            'Mira': 'img/' + fileFormat + '/mira.' + fileFormat,
            'Montagne': 'img/' + fileFormat + '/montagne.' + fileFormat,
            'Mozzie': 'img/' + fileFormat + '/mozzie.' + fileFormat,
            'Mute': 'img/' + fileFormat + '/mute.' + fileFormat,
            'Nøkk': 'img/' + fileFormat + '/nokk.' + fileFormat,
            'Nomad': 'img/' + fileFormat + '/nomad.' + fileFormat,
            'Oryx': 'img/' + fileFormat + '/oryx.' + fileFormat,
            'Osa': 'img/' + fileFormat + '/osa.' + fileFormat,
            'Iana': 'img/' + fileFormat + '/iana.' + fileFormat,
            'Pulse': 'img/' + fileFormat + '/pulse.' + fileFormat,
            'Ram': 'img/' + fileFormat + '/ram.' + fileFormat,
            'Rauora': 'img/' + fileFormat + '/rauora.' + fileFormat,
            'Rook': 'img/' + fileFormat + '/rook.' + fileFormat,
            'Sens': 'img/' + fileFormat + '/sens.' + fileFormat,
            'Sentry': 'img/' + fileFormat + '/sentry.' + fileFormat,
            'Skopós': 'img/' + fileFormat + '/skopos.' + fileFormat,
            'Sledge': 'img/' + fileFormat + '/sledge.' + fileFormat,
            'Smoke': 'img/' + fileFormat + '/smoke.' + fileFormat,
            'Solis': 'img/' + fileFormat + '/solis.' + fileFormat,
            'Striker': 'img/' + fileFormat + '/striker.' + fileFormat,
            'Tachanka': 'img/' + fileFormat + '/tachanka.' + fileFormat,
            'Thatcher': 'img/' + fileFormat + '/thatcher.' + fileFormat,
            'Thermite': 'img/' + fileFormat + '/thermite.' + fileFormat,
            'Thorn': 'img/' + fileFormat + '/thorn.' + fileFormat,
            'Thunderbird': 'img/' + fileFormat + '/thunderbird.' + fileFormat,
            'Tubarão': 'img/' + fileFormat + '/tubarao.' + fileFormat,
            'Twitch': 'img/' + fileFormat + '/twitch.' + fileFormat,
            'Valkyrie': 'img/' + fileFormat + '/valkyrie.' + fileFormat,
            'Vigil': 'img/' + fileFormat + '/vigil.' + fileFormat,
            'Wamai': 'img/' + fileFormat + '/wamai.' + fileFormat,
            'Warden': 'img/' + fileFormat + '/warden.' + fileFormat,
            'Ying': 'img/' + fileFormat + '/ying.' + fileFormat,
            'Zero': 'img/' + fileFormat + '/zero.' + fileFormat,
            'Zofia': 'img/' + fileFormat + '/zofia.' + fileFormat,
        };
    }
}

export default ImageLocation;