class ImageLocation {
    static getLocations(fileFormat) {
        return {
            'Alibi': 'img/' + fileFormat + '/alibi.' + fileFormat,
            'Amaru': 'img/' + fileFormat + '/amaru.' + fileFormat,
            'Ash': 'img/' + fileFormat + '/ash.' + fileFormat,
            'Bandit': 'img/' + fileFormat + '/bandit.' + fileFormat,
            'Blackbeard': 'img/' + fileFormat + '/blackbeard.' + fileFormat,
            'Blitz': 'img/' + fileFormat + '/blitz.' + fileFormat,
            'Buck': 'img/' + fileFormat + '/buck.' + fileFormat,
            'Capitão': 'img/' + fileFormat + '/capitao.' + fileFormat,
            'Castle': 'img/' + fileFormat + '/castle.' + fileFormat,
            'Caveira': 'img/' + fileFormat + '/caveira.' + fileFormat,
            'Clash': 'img/' + fileFormat + '/clash.' + fileFormat,
            'Doc': 'img/' + fileFormat + '/doc.' + fileFormat,
            'Dokkaebi': 'img/' + fileFormat + '/dokkaebi.' + fileFormat,
            'Echo': 'img/' + fileFormat + '/echo.' + fileFormat,
            'Ela': 'img/' + fileFormat + '/ela.' + fileFormat,
            'Finka': 'img/' + fileFormat + '/finka.' + fileFormat,
            'Frost': 'img/' + fileFormat + '/frost.' + fileFormat,
            'Fuze': 'img/' + fileFormat + '/fuze.' + fileFormat,
            'Glaz': 'img/' + fileFormat + '/glaz.' + fileFormat,
            'Goyo': 'img/' + fileFormat + '/goyo.' + fileFormat,
            'Gridlock': 'img/' + fileFormat + '/gridlock.' + fileFormat,
            'Hibana': 'img/' + fileFormat + '/hibana.' + fileFormat,
            'IQ': 'img/' + fileFormat + '/iq.' + fileFormat,
            'Jackal': 'img/' + fileFormat + '/jackal.' + fileFormat,
            'Jäger': 'img/' + fileFormat + '/jager.' + fileFormat,
            'Kaid': 'img/' + fileFormat + '/kaid.' + fileFormat,
            'Kapkan': 'img/' + fileFormat + '/kapkan.' + fileFormat,
            'Lesion': 'img/' + fileFormat + '/lesion.' + fileFormat,
            'Lion': 'img/' + fileFormat + '/lion.' + fileFormat,
            'Maestro': 'img/' + fileFormat + '/maestro.' + fileFormat,
            'Maverick': 'img/' + fileFormat + '/maverick.' + fileFormat,
            'Mira': 'img/' + fileFormat + '/mira.' + fileFormat,
            'Montagne': 'img/' + fileFormat + '/montagne.' + fileFormat,
            'Mozzie': 'img/' + fileFormat + '/mozzie.' + fileFormat,
            'Mute': 'img/' + fileFormat + '/mute.' + fileFormat,
            'Nokk': 'img/' + fileFormat + '/nokk.' + fileFormat,
            'Nomad': 'img/' + fileFormat + '/nomad.' + fileFormat,
            'Pulse': 'img/' + fileFormat + '/pulse.' + fileFormat,
            'Recruit': 'img/' + fileFormat + '/recruit_blue.' + fileFormat,
            'Rook': 'img/' + fileFormat + '/rook.' + fileFormat,
            'Sledge': 'img/' + fileFormat + '/sledge.' + fileFormat,
            'Smoke': 'img/' + fileFormat + '/smoke.' + fileFormat,
            'Tachanka': 'img/' + fileFormat + '/tachanka.' + fileFormat,
            'Thatcher': 'img/' + fileFormat + '/thatcher.' + fileFormat,
            'Thermite': 'img/' + fileFormat + '/thermite.' + fileFormat,
            'Twitch': 'img/' + fileFormat + '/twitch.' + fileFormat,
            'Valkyrie': 'img/' + fileFormat + '/valkyrie.' + fileFormat,
            'Vigil': 'img/' + fileFormat + '/vigil.' + fileFormat,
            'Warden': 'img/' + fileFormat + '/warden.' + fileFormat,
            'Ying': 'img/' + fileFormat + '/ying.' + fileFormat,
            'Zofia': 'img/' + fileFormat + '/zofia.' + fileFormat,
        };
    }
}

export default ImageLocation;